source "http://artifactory.blinkbox.local/artifactory/api/gems/bbb-gems/"
source "http://artifactory.blinkbox.local/artifactory/api/gems/rubygems/"

gem "activerecord", "~> 4.0"
gem "bunny", "~> 0.0", ">= 0.10.8"
gem "geoip", "~> 1.3"
gem "ipaddress", "~> 0.8"
gem "java_properties", "~> 0.0", ">= 0.0.4"
gem "nokogiri", "~> 1.6"
gem "rack-blinkbox-zuul-tokens", ">= 0.0.2"
gem "rack-jsonlogger", ">= 0.1.0"
gem "rack-timekeeper", ">= 0.2.0"
gem "sandal", "~> 0.6"
gem "scrypt", "~> 1.2"
gem "sinatra", "~> 1.2"
gem "sinatra-activerecord", "~> 2.0"
gem "sinatra-contrib", "~> 1.4"
gem "newrelic_rpm", "~> 3.9"

group :development, :test do
  gem "bundler"
  gem "coveralls"
  gem "cucumber"
  gem "cucumber-blinkbox"
  gem "cucumber-helpers"
  gem "cucumber-rest"
  gem "httparty"
  gem "rake"
  gem "rspec", "~>2.99"
  gem "ruby-prof"
  gem "simplecov"
  gem "sqlite3"
  gem "yard"
  gem "thin"
  gem "rack-test"
  gem "timecop"
end

group :mysql do
  gem "mysql2", "~> 0.3", ">= 0.3.13"
end